os:
  - linux
  - osx

env:
  - GO111MODULE=on

addons:
  apt:
    packages:
      - libappindicator3-dev
      - gcc
      - libgtk-3-dev

jobs:
  include:
    - stage: frontend-prepare
      language: node_js
      node_js:
        - 12
      script:
        - cd frontend
        - npm install
    - stage: app-bundle
      language: go
      go:
        - 1.14
      script:
        - go run build.go build
