language: generic

os:
  - linux
  - osx

env:
  - GO111MODULE=on

addons:
  apt:
    packages:
      - libappindicator3-dev
      - gcc
      - libgtk-3-dev

jobs:
  include:
    - stage: test
      language: go
      go:
        - 1.14
      script: go test -v ./...
    - stage: app-bundle
      language: go
      go:
        - 1.14
      before_script:
        - nvm install --lts
        - nvm use --lts
      script:
        - cd frontend && npm install && cd .. && go run build.go build
