language: go

go:
  - 1.14

os:
  - linux
  - osx

env:
  - GO111MODULE=on

addons:
  apt:
    packages:
      - libappindicator3-dev
      - gcc
      - libgtk-3-dev

before_script:
  - nvm install --lts
  - nvm use --lts
script:
  - go test -v ./...
  - cd frontend && npm install && cd .. && go run build.go build
