os:
  - linux
  - osx

language: go
go:
  - 1.14

node_js:
  - 12

env:
  - GO111MODULE=on

addons:
  apt:
    packages:
      - libappindicator3-dev
      - gcc
      - libgtk-3-dev

script:
  - cd frontend
  - npm install
  - cd ..
  - go run build.go build