name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: "Run Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Install dependencies for Ubuntu
      run: sudo apt update && sudo apt install -y libappindicator3-dev gcc libgtk-3-dev libxapp-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Test
      run: go test -v ./...

    - name: Update GoReport card
      run: curl -d "repo=github.com/Cloaklet/Cloak" https://goreportcard.com/checks